name: GSA IAE
markdown: kramdown
pygments: true
safe: true
baseurl: /openIAE
exclude: ['.ruby-version', 'node_modules', 'package.json', 'bower.json']

permalink: pretty

sass:
  sass_dir: assets/_scss
#  style: :compressed
